server:
  port: 8082
  path: /hello


person:
    lastName: li
    age: 20
    boss: false
    birth: 2019/7/29
    maps:
      k1: v1
      k2: v2
    lists:
      - lisi
      - zhaosi
    dog:
      name: 小狗
      age: 2
##关闭缓存，即时刷新
##spring.freemaker.cashe=false
spring:
  thymeleaf:
    cache: false
  freemarker:
    cache: false
#  spring.thymeleaf.cache=true